import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export const getStaticProps=async ()=>{
  let abc=await fetch('https://eonet.sci.gsfc.nasa.gov/api/v2.1/events')
  let unr=await abc.json()
  return {
    props:{data:unr}
  }
}

export default function Home({data}) {
  let x = data.events
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <ul>
         {x.map(a=>{
           return(
            <li>
            <Link href={'/ninjas/'+a.id}>
              <a>page {a.id}</a>
            </Link>
          </li>
           )
         })}
        </ul>
    </div>
  )
}
